name: jarvis
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.0.0
  provider: ^6.1.1
  image_picker: ^0.8.4+4
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.2.1
  flutter_slidable: ^3.1.1
  dio: ^5.0.0
  uuid: ^3.0.0
  intl: ^0.19.0
  flutter_markdown: ^0.6.18
  url_launcher: ^6.1.14
  permission_handler: ^11.0.0
  screenshot: ^3.0.0
  path_provider: ^2.1.5
  ffi: ^2.1.3
  google_mobile_ads: ^4.0.0
  file_picker: ^8.1.6
  google_sign_in: ^6.2.2
  firebase_core: ^3.9.0
  firebase_analytics: ^11.3.6
  rename: ^3.0.2
  in_app_purchase: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
flutter_icons:
  image_path: "assets/logoAI.png"
  android: true
  ios: true
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logoAI.png
    - assets/images/
    - assets/images/splash-screen-image.png
    - assets/images/splash-top-icon.png
    - assets/logo/
